PRODUCT_COPY_FILES += \
    vendor/moto/panelli/proprietary/bin/mtkrildmd2:system/bin/mtkrildmd2 \
    vendor/moto/panelli/proprietary/bin/xlog:system/bin/xlog \
    vendor/moto/panelli/proprietary/bin/uiautomator:system/bin/uiautomator \
    vendor/moto/panelli/proprietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
    vendor/moto/panelli/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/moto/panelli/proprietary/bin/muxreport:system/bin/muxreport \
    vendor/moto/panelli/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/moto/panelli/proprietary/bin/msensord:system/bin/msensord \
    vendor/moto/panelli/proprietary/bin/mdlogger:system/bin/mdlogger \
    vendor/moto/panelli/proprietary/bin/terservice:system/bin/terservice \
    vendor/moto/panelli/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/moto/panelli/proprietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/moto/panelli/proprietary/bin/mtkrild:system/bin/mtkrild \
    vendor/moto/panelli/proprietary/bin/thermald:system/bin/thermald \
    vendor/moto/panelli/proprietary/bin/thermal:system/bin/thermal \
    vendor/moto/panelli/proprietary/bin/bmm050d:system/bin/bmm050d \
    vendor/moto/panelli/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/moto/panelli/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/moto/panelli/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/moto/panelli/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/moto/panelli/proprietary/bin/mc6420d:system/bin/mc6420d \
    vendor/moto/panelli/proprietary/bin/lsm303md:system/bin/lsm303md \
    vendor/moto/panelli/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/moto/panelli/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/moto/panelli/proprietary/bin/md_ctrl:system/bin/md_ctrl \
    vendor/moto/panelli/proprietary/bin/lcdc_screen_cap:system/bin/lcdc_screen_cap \
    vendor/moto/panelli/proprietary/bin/gsm0710muxdmd2:system/bin/gsm0710muxdmd2 \
    vendor/moto/panelli/proprietary/bin/pppd:system/bin/pppd \
    vendor/moto/panelli/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/moto/panelli/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/moto/panelli/proprietary/bin/program_binary_service:system/bin/program_binary_service \
    vendor/moto/panelli/proprietary/bin/guiext-server:system/bin/guiext-server \
    vendor/moto/panelli/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/moto/panelli/proprietary/bin/mtkmal:system/bin/mtkmal \
    vendor/moto/panelli/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/moto/panelli/proprietary/bin/gas_srv:system/bin/gas_srv \
    vendor/moto/panelli/proprietary/bin/ged_srv:system/bin/ged_srv \
    vendor/moto/panelli/proprietary/bin/memorydumper:system/bin/memorydumper \
    vendor/moto/panelli/proprietary/bin/mmp:system/bin/mmp \
    vendor/moto/panelli/proprietary/bin/MATest:system/bin/MATest \
    vendor/moto/panelli/proprietary/bin/matv:system/bin/matv \
    vendor/moto/panelli/proprietary/bin/magd:system/bin/magd \
    vendor/moto/panelli/proprietary/bin/memsicd3416x:system/bin/memsicd3416x \
    vendor/moto/panelli/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/moto/panelli/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/moto/panelli/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/moto/panelli/proprietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
    vendor/moto/panelli/proprietary/bin/aee:system/bin/aee \
    vendor/moto/panelli/proprietary/bin/aee_archive:system/bin/aee_archive \
    vendor/moto/panelli/proprietary/bin/aee_core_forwarder:system/bin/aee_core_forwarder \
    vendor/moto/panelli/proprietary/bin/aee_dumpstate:system/bin/aee_dumpstate \
    vendor/moto/panelli/proprietary/bin/sn:system/bin/sn \
    vendor/moto/panelli/proprietary/bin/slpd:system/bin/slpd \
    vendor/moto/panelli/proprietary/bin/pppd_dt:system/bin/pppd_dt \
    vendor/moto/panelli/proprietary/bin/wifi2agps:system/bin/wifi2agps \
    vendor/moto/panelli/proprietary/bin/memsicd:system/bin/memsicd \
    vendor/moto/panelli/proprietary/bin/memsicp:system/bin/memsicp \
    vendor/moto/panelli/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/moto/panelli/proprietary/bin/s62xd:system/bin/s62xd \
    vendor/moto/panelli/proprietary/bin/mobile_log_d:system/bin/mobile_log_d \
    vendor/moto/panelli/proprietary/bin/netdiag:system/bin/netdiag \
    vendor/moto/panelli/proprietary/bin/NativeMisc:system/bin/NativeMisc \
    vendor/moto/panelli/proprietary/bin/pq:system/bin/pq \
    vendor/moto/panelli/proprietary/bin/perf_native_test:system/bin/perf_native_test \
    vendor/moto/panelli/proprietary/bin/ppl_agent:system/bin/ppl_agent \
    vendor/moto/panelli/proprietary/bin/radvd:system/bin/radvd \
    vendor/moto/panelli/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/moto/panelli/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/moto/panelli/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/moto/panelli/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/moto/panelli/proprietary/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxVdecEx.so:system/lib/libMtkOmxVdecEx.so \
    vendor/moto/panelli/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/moto/panelli/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/moto/panelli/proprietary/lib/libem_support_jni.so:system/lib/libem_support_jni.so \
    vendor/moto/panelli/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/moto/panelli/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/moto/panelli/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/moto/panelli/proprietary/lib/libfeatureiodrv.so:system/lib/libfeatureiodrv.so \
    vendor/moto/panelli/proprietary/lib/libem_modem_jni.so:system/lib/libem_modem_jni.so \
    vendor/moto/panelli/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/moto/panelli/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/moto/panelli/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/moto/panelli/proprietary/lib/libui_ext.so:system/lib/libui_ext.so \
    vendor/moto/panelli/proprietary/lib/libh264enc_sa.ca7.so:system/lib/libh264enc_sa.ca7.so \
    vendor/moto/panelli/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/moto/panelli/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/moto/panelli/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/moto/panelli/proprietary/lib/libem_bt_jni.so:system/lib/libem_bt_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_gpio_jni.so:system/lib/libem_gpio_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_lte_jni.so:system/lib/libem_lte_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_modem_jni.so:system/lib/libem_modem_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_sensor_jni.so:system/lib/libem_sensor_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_support_jni.so:system/lib/libem_support_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_usb_jni.so:system/lib/libem_usb_jni.so \
    vendor/moto/panelli/proprietary/lib/libem_wifi_jni.so:system/lib/libem_wifi_jni.so \
    vendor/moto/panelli/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/moto/panelli/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/moto/panelli/proprietary/lib/libem_gpio_jni.so:system/lib/libem_gpio_jni.so \
    vendor/moto/panelli/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/moto/panelli/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/moto/panelli/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/moto/panelli/proprietary/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/moto/panelli/proprietary/lib/libmdloggerrecycle.so:system/lib/libmdloggerrecycle.so \
    vendor/moto/panelli/proprietary/lib/libmdfx.so:system/lib/libmdfx.so \
    vendor/moto/panelli/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/moto/panelli/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/moto/panelli/proprietary/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
    vendor/moto/panelli/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/moto/panelli/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/moto/panelli/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/moto/panelli/proprietary/lib/libmal.so:system/lib/libmal.so \
    vendor/moto/panelli/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/moto/panelli/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/moto/panelli/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/moto/panelli/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/moto/panelli/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/moto/panelli/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/moto/panelli/proprietary/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/moto/panelli/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/moto/panelli/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/moto/panelli/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/moto/panelli/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/moto/panelli/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/moto/panelli/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/moto/panelli/proprietary/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/moto/panelli/proprietary/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    vendor/moto/panelli/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/moto/panelli/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/moto/panelli/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/moto/panelli/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/moto/panelli/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/moto/panelli/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/moto/panelli/proprietary/lib/libged.so:system/lib/libged.so \
    vendor/moto/panelli/proprietary/lib/libem_usb_jni.so:system/lib/libem_usb_jni.so \
    vendor/moto/panelli/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/moto/panelli/proprietary/lib/libem_wifi_jni.so:system/lib/libem_wifi_jni.so \
    vendor/moto/panelli/proprietary/lib/libccci_util.so:system/lib/libccci_util.so \
    vendor/moto/panelli/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/moto/panelli/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/moto/panelli/proprietary/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
    vendor/moto/panelli/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/moto/panelli/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
    vendor/moto/panelli/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/moto/panelli/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/moto/panelli/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
    vendor/moto/panelli/proprietary/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/moto/panelli/proprietary/lib/libem_lte_jni.so:system/lib/libem_lte_jni.so \
    vendor/moto/panelli/proprietary/lib/drm/libdrmctaplugin.so:system/lib/drm/libdrmctaplugin.so \
    vendor/moto/panelli/proprietary/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so \
    vendor/moto/panelli/proprietary/lib/hw/memtrack.mt6737m.so:system/lib/hw/memtrack.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/camera.mt6737m.so:system/lib/hw/camera.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/moto/panelli/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/moto/panelli/proprietary/lib/hw/hwcomposer.mt6737m.so:system/lib/hw/hwcomposer.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/audio.primary.mt6737m.so:system/lib/hw/audio.primary.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
    vendor/moto/panelli/proprietary/lib/hw/gralloc.mt6737m.so:system/lib/hw/gralloc.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/moto/panelli/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/moto/panelli/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    vendor/moto/panelli/proprietary/lib/hw/lights.mt6737m.so:system/lib/hw/lights.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/hw/radio.fm.mt6737m.so:system/lib/hw/radio.fm.mt6737m.so \
    vendor/moto/panelli/proprietary/lib/libpqservice.so:system/lib/libpqservice.so \
    vendor/moto/panelli/proprietary/lib/libgas.so:system/lib/libgas.so \
    vendor/moto/panelli/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/moto/panelli/proprietary/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/moto/panelli/proprietary/lib/libcamdrv_FrmB.so:system/lib/libcamdrv_FrmB.so \
    vendor/moto/panelli/proprietary/lib/libfs_mgr.so:system/lib/libfs_mgr.so \
    vendor/moto/panelli/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/moto/panelli/proprietary/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/moto/panelli/proprietary/lib/libterservice.so:system/lib/libterservice.so \
    vendor/moto/panelli/proprietary/lib/libimageio_plat_drv_FrmB.so:system/lib/libimageio_plat_drv_FrmB.so \
    vendor/moto/panelli/proprietary/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/moto/panelli/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
    vendor/moto/panelli/proprietary/lib/liba3m.so:system/lib/liba3m.so \
    vendor/moto/panelli/proprietary/lib/libacdk.so:system/lib/libacdk.so \
    vendor/moto/panelli/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/moto/panelli/proprietary/lib/libhdrproc.so:system/lib/libhdrproc.so \
    vendor/moto/panelli/proprietary/lib/libimageio_FrmB.so:system/lib/libimageio_FrmB.so \
    vendor/moto/panelli/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/moto/panelli/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/moto/panelli/proprietary/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/moto/panelli/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/moto/panelli/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/moto/panelli/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/moto/panelli/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/moto/panelli/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
    vendor/moto/panelli/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/moto/panelli/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/moto/panelli/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/moto/panelli/proprietary/lib/libperfservice.so:system/lib/libperfservice.so \
    vendor/moto/panelli/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/moto/panelli/proprietary/lib/libcam.hal3a.v3.dng.so:system/lib/libcam.hal3a.v3.dng.so \
    vendor/moto/panelli/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/moto/panelli/proprietary/lib/libgpu_aux.so:system/lib/libgpu_aux.so \
    vendor/moto/panelli/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/moto/panelli/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/moto/panelli/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/moto/panelli/proprietary/lib/libem_bt_jni.so:system/lib/libem_bt_jni.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/moto/panelli/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/moto/panelli/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/moto/panelli/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/moto/panelli/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/moto/panelli/proprietary/lib/libHEVCdec_sa.ca7.android.so:system/lib/libHEVCdec_sa.ca7.android.so \
    vendor/moto/panelli/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/moto/panelli/proprietary/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
    vendor/moto/panelli/proprietary/lib/libmmsdkservice.feature.so:system/lib/libmmsdkservice.feature.so \
    vendor/moto/panelli/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/moto/panelli/proprietary/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    vendor/moto/panelli/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/moto/panelli/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/moto/panelli/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    vendor/moto/panelli/proprietary/lib/libmp4enc_xa.ca7.so:system/lib/libmp4enc_xa.ca7.so \
    vendor/moto/panelli/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/moto/panelli/proprietary/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/moto/panelli/proprietary/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/moto/panelli/proprietary/lib/libpq_prot.so:system/lib/libpq_prot.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/moto/panelli/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/moto/panelli/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/moto/panelli/proprietary/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/moto/panelli/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/moto/panelli/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/moto/panelli/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/moto/panelli/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/moto/panelli/proprietary/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/moto/panelli/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/moto/panelli/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/moto/panelli/proprietary/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/moto/panelli/proprietary/lib/libem_sensor_jni.so:system/lib/libem_sensor_jni.so \
    vendor/moto/panelli/proprietary/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/moto/panelli/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/moto/panelli/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/moto/panelli/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
    vendor/moto/panelli/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/moto/panelli/proprietary/etc/audio_device.xml:system/etc/audio_device.xml \
    vendor/moto/panelli/proprietary/etc/agps_profiles_conf2.xml:system/etc/agps_profiles_conf2.xml \
    vendor/moto/panelli/proprietary/etc/perfservscntbl.txt:system/etc/perfservscntbl.txt \
    vendor/moto/panelli/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/moto/panelli/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/moto/panelli/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/moto/panelli/proprietary/vendor/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/vendor/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/modem_1_lwg_n.img:system/vendor/firmware/modem_1_lwg_n.img \
    vendor/moto/panelli/proprietary/vendor/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/vendor/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/vendor/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v5_patch.bin:system/vendor/firmware/mt6627/mt6627_fm_v5_patch.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/vendor/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v2_patch.bin:system/vendor/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/vendor/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v3_patch.bin:system/vendor/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/vendor/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v4_patch.bin:system/vendor/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/vendor/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/mt6627/mt6627_fm_v1_patch.bin:system/vendor/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/catcher_filter_1_lwg_n.bin:system/vendor/firmware/catcher_filter_1_lwg_n.bin \
    vendor/moto/panelli/proprietary/vendor/firmware/WMT_SOC.cfg:system/vendor/firmware/WMT_SOC.cfg \
    vendor/moto/panelli/proprietary/vendor/firmware/WIFI_RAM_CODE_6735:system/vendor/firmware/WIFI_RAM_CODE_6735 \
    vendor/moto/panelli/proprietary/vendor/firmware/dsp_1_lwg_n.bin:system/vendor/firmware/dsp_1_lwg_n.bin \
    vendor/moto/panelli/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/moto/panelli/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/moto/panelli/proprietary/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
    vendor/moto/panelli/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
    vendor/moto/panelli/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
    vendor/moto/panelli/proprietary/usr/keylayout/ACCDET.kl:system/usr/keylayout/ACCDET.kl \
    vendor/moto/panelli/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/moto/panelli/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/moto/panelli/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/moto/panelli/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/moto/panelli/proprietary/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/moto/panelli/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/moto/panelli/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/moto/panelli/proprietary/xbin/mnld:system/xbin/mnld \
    vendor/moto/panelli/proprietary/xbin/BGW:system/xbin/BGW
